"""Static legal / E-E-A-T pages rendered into docs/."""

from datetime import date

UPDATED = date(2026, 8, 26).isoformat()

PRIVACY_BODY = """
<p>This Privacy Policy explains how <strong>J-Anime Radar</strong> (“we”, “us”, “the site”) collects, uses, and discloses information when you visit our English-language anime intelligence publication. We designed this policy to meet the disclosure expectations of Google AdSense, Google Analytics, and comparable advertising / measurement partners.</p>

<h2>1. Who we are</h2>
<p>J-Anime Radar is an independent editorial project that publishes original episode briefings, craft analysis, and Japanese fandom context for currently airing anime. We operate a static website (typically hosted on GitHub Pages or Cloudflare Pages). We do not require user accounts to read the site.</p>

<h2>2. Information we collect</h2>
<p>We do not run a first-party membership database. Information we may process includes:</p>
<ul>
  <li><strong>Technical logs</strong> generated by our host or CDN (IP address, browser type, device, referring URL, timestamps) for security and reliability.</li>
  <li><strong>Usage and approximate location data</strong> collected by analytics cookies or similar technologies if Google Analytics (or a comparable tool) is enabled.</li>
  <li><strong>Advertising identifiers and cookie data</strong> set by Google and other certified third-party vendors when ads are served.</li>
  <li><strong>Messages you send us</strong> through the Contact page, Google Form, or email, including copyright notices from rights holders.</li>
</ul>
<p>We do not knowingly collect personal information from children. The site is intended for a general audience, including teens and adults who follow television anime. Some titles we cover contain mature themes; that does not change our data practices.</p>

<h2>3. Cookies and similar technologies</h2>
<p>Cookies are small text files stored on your device. We and our partners use cookies, pixels, and local storage to:</p>
<ul>
  <li>remember basic site preferences;</li>
  <li>measure readership and improve article usefulness;</li>
  <li>deliver, limit, and report on advertisements, including personalized ads where permitted.</li>
</ul>
<p>You can refuse or delete cookies in your browser settings. Blocking cookies may limit analytics accuracy and, where ads are shown, the relevance of those ads.</p>

<h2>4. Google AdSense and third-party advertising</h2>
<p>We use Google AdSense to display advertisements. Third-party vendors, including Google, use cookies to serve ads based on a user’s prior visits to this website or other websites. Google’s use of advertising cookies enables it and its partners to serve ads to you based on your visit to this site and/or other sites on the Internet.</p>
<p>Users may opt out of personalized advertising by visiting <a href="https://www.google.com/settings/ads" rel="noopener noreferrer" target="_blank">Google Ads Settings</a>. Alternatively, you can opt out of some third-party vendors’ uses of cookies for personalized advertising by visiting <a href="https://www.aboutads.info/choices/" rel="noopener noreferrer" target="_blank">www.aboutads.info</a> or the European <a href="https://www.youronlinechoices.eu/" rel="noopener noreferrer" target="_blank">Your Online Choices</a> page.</p>
<p>We also follow Google’s publisher requirements regarding:</p>
<ul>
  <li>clear labeling of advertisements versus editorial content;</li>
  <li>prohibiting clicks on ads by site operators;</li>
  <li>not placing ads on pages that exist only to show ads, or that lack substantial original content;</li>
  <li>disclosing that third parties, including Google, may serve ads and use cookies as described above.</li>
</ul>
<p>Google, as a third-party vendor, uses cookies to serve ads on this site. Third-party vendors and ad networks other than Google may also serve ads. You should consult those vendors’ policies if additional networks are added later; this page will be updated if that happens.</p>

<h2>5. Google Analytics and traffic measurement</h2>
<p>If Google Analytics is installed, it uses cookies to help us understand aggregated traffic: which briefings are read, approximate geography, device class, and referral sources. Google Analytics may process data on Google’s servers. We use this information to decide which titles deserve deeper coverage and to keep the site useful—not to sell a marketing list.</p>
<p>You can opt out of Google Analytics using the <a href="https://tools.google.com/dlpage/gaoptout" rel="noopener noreferrer" target="_blank">Google Analytics Opt-out Browser Add-on</a> where available, or by blocking analytics cookies.</p>
<p>We may also use privacy-oriented alternatives (for example, server-side or cookieless counters) in the future. Any material change will be reflected in the “Last updated” date on this page.</p>

<h2>6. Legal bases and international readers</h2>
<p>Depending on your location, we rely on legitimate interests (running a publication, keeping it secure, measuring audience, funding it with ads) and/or consent for non-essential cookies and personalized advertising. Readers in the EEA, UK, or similar jurisdictions may have rights to access, correct, delete, or restrict personal data, and to object to certain processing. Advertising consent, where required, is handled through the consent message associated with our ad or CMP configuration.</p>

<h2>7. How long we keep information</h2>
<p>Host logs are retained only as long as needed for security and operations. Analytics data follows the retention settings of the relevant product. Correspondence you send us is kept as long as needed to answer you, document a rights complaint, or meet legal obligations.</p>

<h2>8. Sharing</h2>
<p>We do not sell mailing lists. We share data with processors who host the site, serve ads, or measure traffic (for example Google, GitHub, Cloudflare), and if required by law. Production committees and licensors are not given your personal data merely because we covered their title.</p>

<h2>9. Security</h2>
<p>No static site can guarantee absolute security. We limit collection, use HTTPS where the host provides it, and avoid storing payment data.</p>

<h2>10. Contact about privacy</h2>
<p>Questions about this policy, cookie use, or a data request can be sent through our <a href="contact.html">Contact</a> page. Please write “Privacy” in the subject line.</p>
"""

ABOUT_BODY = """
<p><strong>J-Anime Radar</strong> is an overseas-facing intelligence desk for the Japanese television anime season. Our catchphrase is simple: <em>Seasonal Anime Intel, Episode Breakdowns &amp; Japanese Fan Reactions</em>.</p>

<h2>Mission</h2>
<p>Too much English-language seasonal coverage is either a plot paraphrase or a scoreboard. We publish original briefings that a demanding reader can actually use: how an episode was staged, what Japanese viewers argued about the same night, which performances landed, and where the episode sits in the cour. We exist so international fans can read Japan’s week with context—not a copied synopsis.</p>
<p>We track the current season’s most-watched cluster (our working set is the live Top 30) and update when a new episode appears. The desk is built as a static site so pages stay fast, archivable, and suitable for long-form reading.</p>
<p>The Season Top 30 sidebar is a live popularity snapshot, not a Nielsen-style Japanese TV ratings table and not an editorial ranking. We pull currently airing TV/ONA titles from <a href="https://anilist.co/" rel="noopener noreferrer">AniList</a> (sort: popularity), merging this cour with last cour so 2-cour series that started previously are not dropped. If that feed is down, we use <a href="https://jikan.moe/" rel="noopener noreferrer">Jikan</a> / <a href="https://myanimelist.net/" rel="noopener noreferrer">MyAnimeList</a> current-season listings with continuing titles included. Scores shown are public community averages.</p>

<h2>What “original” means here</h2>
<p>Each briefing is structured around craft and reception, not a beat-by-beat recap:</p>
<ul>
  <li><strong>Story inflection</strong> — turning points, theme, and dramatic function, written as criticism.</li>
  <li><strong>Sakuga and direction</strong> — animation quality, action grammar, camera, cut density, and studio fingerprint.</li>
  <li><strong>Story and lore</strong> — adaptation choices, foreshadowing, and how Japanese fans parsed the week.</li>
  <li><strong>Voice acting</strong> — seiyuu craft, standout line readings, and discussion around the cast.</li>
  <li><strong>Season takeaway</strong> — why the episode matters to the cour as a whole.</li>
  <li><strong>Legal watch links</strong> — licensed platforms only. We never host or link to piracy.</li>
</ul>

<h2>Data sources and official metadata</h2>
<p>Schedule metadata, popularity order, scores, studios, and poster art are drawn from public catalog APIs—primarily <strong>Jikan</strong> (an unofficial MyAnimeList API) with <strong>AniList</strong> as a reliability fallback when Jikan is unavailable. Those catalogs aggregate community and industry-visible facts (titles, episode counts, broadcast windows). They do not write our criticism.</p>
<p>We treat catalog scores as a public weather report, not as our grade. A title can sit at rank 14 and still receive a serious briefing if the episode is doing interesting work.</p>

<h2>Curatorial process (human standards + AI assistance)</h2>
<p>To keep coverage timely across twenty concurrent series, we use a documented pipeline:</p>
<ol>
  <li><strong>Detect</strong> newly aired episodes against <code>data/anime_tracker.json</code> so we never regenerate a finished briefing.</li>
  <li><strong>Ground</strong> the draft in catalog facts: title, episode number, studio, genres, main cast, and licensed platforms.</li>
  <li><strong>Draft</strong> a long-form English JSON package (500+ words) with Google Gemini (<code>gemini-1.5-flash</code> or a current Flash successor). The model is instructed to refuse thin recaps, to write criticism, and to separate Japanese reception from plot paraphrase.</li>
  <li><strong>Shape</strong> the draft into article HTML with stable headings, metadata, Open Graph tags, and Schema.org JSON-LD (<em>WebSite</em>, <em>Article</em>, <em>TVEpisode</em>).</li>
  <li><strong>Publish</strong> as static files. Editors remain responsible for tone, corrections, and takedown requests.</li>
</ol>
<p>AI is an acceleration layer, not a hidden authorial identity. We do not present generated text as an interview with a production staffer, and we do not fabricate quotes from named fans. Japanese reaction sections describe patterns typical of the title’s actual fandom (sakuga accounts, broadcast-night timeline talk, seiyuu discussion) rather than invented viral posts.</p>

<h2>Experience, expertise, authoritativeness, trust (E-E-A-T)</h2>
<p>The desk is built so a reviewer—or a reader—can inspect our method:</p>
<ul>
  <li><strong>Experience</strong> — we cover the live season at episode granularity, with Japanese reception as a first-class beat, not a sidebar.</li>
  <li><strong>Expertise</strong> — briefings are organized the way animators and critics actually talk: sakuga, staging, adaptation, performance.</li>
  <li><strong>Authoritativeness</strong> — we cite public catalog data, name studios and credited seiyuu, and point only to licensed services.</li>
  <li><strong>Trust</strong> — Privacy, Contact, and Disclaimer pages are linked in the footer of every document. Copyright complaints have a dedicated path. We label advertising when AdSense is live. We correct errors when they are shown to us.</li>
</ul>

<h2>Independence</h2>
<p>J-Anime Radar is not paid by production committees to rank titles. If a sponsored disclosure ever becomes necessary, it will be labeled on the relevant page. Advertisements, when enabled, are visually separate from editorial briefings.</p>

<h2>Operator</h2>
<p>The publication is operated by the <strong>J-Anime Radar Editorial Project</strong>, an independent media desk covering Japanese television animation for an international audience. We do not claim to represent Kodansha, Shueisha, Kadokawa, any production committee, or any streaming platform.</p>
<p>Press, corrections, and rights-holder mail: use <a href="contact.html">Contact</a>.</p>
"""

CONTACT_BODY = """
<p>Use this desk if you are a reader with a correction, a journalist, a licensed platform, or a rights holder. We read editorial and legal mail. We do not offer piracy help, leak trading, or unofficial download links.</p>

<h2>Readers and press</h2>
<p>Tell us the article URL, the episode number, and what needs a second look. Useful mail includes factual errors in metadata (studio, episode count, platform) and good-faith disagreements about craft that cite the episode rather than insults.</p>
<p>Editorial email: <a href="mailto:{{ contact_email }}">{{ contact_email }}</a></p>

<h2>Rights holders and copyright agents</h2>
<p>If you represent a production committee, publisher, licensor, or performer and believe a page exceeds legitimate criticism or uses an asset you want removed, send a notice that includes:</p>
<ul>
  <li>your name, role, and a contact email;</li>
  <li>the work and the specific URL(s);</li>
  <li>a description of the material (for example a key visual you want taken down);</li>
  <li>a statement that you are authorized to act for the owner;</li>
  <li>a good-faith signature (typed name is acceptable in email).</li>
</ul>
<p>We aim to review valid notices promptly. Our default is to preserve criticism and to remove or replace assets that are not needed for commentary. We will not keep unauthorized episode video; this site does not host video files.</p>

<h2>Contact form</h2>
<p>The form below is the public inbox. If the embedded Google Form does not load, open <a href="https://forms.gle/Eh6uh7b2BC6P3qEz6" rel="noopener noreferrer" target="_blank">the contact form</a> in a new tab.</p>
{% if form_embed %}
<iframe class="contact-frame" title="Contact J-Anime Radar" src="{{ form_embed }}" width="100%" height="920" frameborder="0" marginheight="0" marginwidth="0">Loading contact form…</iframe>
{% else %}
<form class="reaction" method="post" action="https://formsubmit.co/{{ contact_email }}">
  <p><label>Name<br><input name="name" required style="width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#0b1018;color:inherit"></label></p>
  <p><label>Email<br><input type="email" name="email" required style="width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#0b1018;color:inherit"></label></p>
  <p><label>Subject<br>
    <select name="subject" style="width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#0b1018;color:inherit">
      <option>Reader correction</option>
      <option>Press inquiry</option>
      <option>Rights holder / copyright</option>
      <option>Privacy request</option>
      <option>Other</option>
    </select>
  </label></p>
  <p><label>Message<br><textarea name="message" required rows="8" style="width:100%;padding:10px;border-radius:10px;border:1px solid var(--line);background:#0b1018;color:inherit"></textarea></label></p>
  <p><button class="chip is-on" type="submit">Send message</button></p>
  <input type="hidden" name="_subject" value="J-Anime Radar contact">
  <input type="hidden" name="_template" value="table">
</form>
<p class="tiny">Replace the Google Form embed URL in <code>.env</code> (<code>GOOGLE_FORM_EMBED_URL</code>) to use your own Google Form instead of this fallback.</p>
{% endif %}

<h2>Response time</h2>
<p>Reader mail is handled as capacity allows. Copyright notices are prioritized over general fandom debate.</p>
"""

DISCLAIMER_BODY = """
<p>Please read this page before relying on any briefing. It is part of our contract with readers and with the owners of the works we discuss.</p>

<h2>1. Copyright belongs to the original owners</h2>
<p>Anime titles, characters, names, logos, key visuals, promotional stills, scripts, music, and related trademarks are the property of their respective <strong>production committees, original authors, publishers, music publishers, and licensed distributors</strong>. Examples include—but are not limited to—the committees behind <em>Mushoku Tensei</em>, <em>BLEACH</em>, <em>Ghost in the Shell</em>, <em>Saga of Tanya the Evil</em>, and every other series listed on this site. J-Anime Radar does not claim those rights.</p>
<p>Cover and banner images displayed for identification are loaded from public catalog sources (such as AniList) for reporting and commentary. They remain the property of the original rights holders. If an owner wants a specific image removed, use the <a href="contact.html">Contact</a> page.</p>

<h2>2. Fair use / fair dealing — criticism and news</h2>
<p>Our episode pages are <strong>criticism, commentary, and news reporting</strong> about contemporaneous television broadcasts. We describe craft, reception, and legal availability. We do not reproduce episode video, full scripts, or scanlated pages. Short references to plot function are included only as needed to make the criticism intelligible.</p>
<p>Where U.S. fair use (17 U.S.C. § 107) or comparable doctrines apply, we rely on the purpose of criticism, the transformative nature of original analysis, the limited amount used, and the fact that we send readers to <em>licensed</em> platforms rather than substituting for them.</p>

<h2>3. No unofficial streams</h2>
<p>We will not link to pirate sites, aggregation indexes, “watch free” mirrors, or unofficial Discord rips. If a briefing mentions a platform, it is because that platform is a known licensed outlet or an official information page. Geo-availability changes; always confirm in your country.</p>

<h2>4. Editorial independence and no endorsement</h2>
<p>Coverage is not an endorsement by the studio, committee, or streamer. Rankings on the homepage reflect public popularity metrics from catalog APIs, not a paid chart. Scores are community figures and can move.</p>

<h2>5. Spoilers</h2>
<p>Episode briefings discuss the dramatic function of recently aired television. If you are not caught up, do not open the episode page. We do not exist to leak unaired cuts or confidential production memos.</p>

<h2>6. Accuracy and AI-assisted drafts</h2>
<p>Metadata is sourced from public APIs and can lag or contain errors. Narrative analysis is original editorial work and, on the daily pipeline, may be drafted with assistance from a large language model under a strict anti-thin-content prompt. Models can be wrong about a cut, a credit, or a rumor. We do not treat generated text as a primary historical record. If something is factually off, tell us.</p>
<p>Japanese fan-reaction sections summarize <em>types</em> of conversation that surround a title (sakuga timelines, seiyuu talk, adaptation arguments). They are not a transcript of private messages and should not be read as a scientific poll of all Japanese viewers.</p>

<h2>7. Disclaimer of liability</h2>
<p>The site is provided “as is.” To the maximum extent permitted by law, the J-Anime Radar Editorial Project is not liable for decisions you make based on a briefing, for third-party ads or cookies, for outages at GitHub/Cloudflare/Google, or for trademark disputes among other parties. Nothing here is legal, financial, or medical advice.</p>

<h2>8. Adult themes and reader discretion</h2>
<p>Some tracked titles include violence, war, sexualized comedy, or other mature content. We may mention that tone; we do not provide illegal content. Parents and sensitive readers should check ratings on the licensed platform.</p>

<h2>9. Trademarks</h2>
<p>“J-Anime Radar” is the name of this publication. Other names are used for identification only.</p>

<h2>10. Changes</h2>
<p>We may update this page as the catalog of titles or our hosting stack changes. The date at the top is the latest revision.</p>
"""


def page_specs():
    return [
        {
            "filename": "privacy.html",
            "nav": "privacy",
            "kicker": "Legal",
            "heading": "Privacy Policy",
            "title": "Privacy Policy — J-Anime Radar",
            "description": "How J-Anime Radar uses cookies, Google AdSense, Google Analytics, and other measurement or advertising technologies.",
            "body": PRIVACY_BODY,
            "updated": UPDATED,
        },
        {
            "filename": "about.html",
            "nav": "about",
            "kicker": "Editorial",
            "heading": "About Us & Editorial Policy",
            "title": "About Us & Editorial Policy — J-Anime Radar",
            "description": "Mission, catalog data policy, and the AI-assisted curatorial process behind J-Anime Radar episode briefings.",
            "body": ABOUT_BODY,
            "updated": UPDATED,
        },
        {
            "filename": "contact.html",
            "nav": "contact",
            "kicker": "Desk",
            "heading": "Contact Us",
            "title": "Contact Us — J-Anime Radar",
            "description": "Contact the J-Anime Radar editorial desk for corrections, press, privacy requests, or rights-holder notices.",
            "body": CONTACT_BODY,
            "updated": UPDATED,
        },
        {
            "filename": "disclaimer.html",
            "nav": "disclaimer",
            "kicker": "Legal",
            "heading": "Copyright & Disclaimer",
            "title": "Copyright & Disclaimer — J-Anime Radar",
            "description": "Copyright ownership, fair-use criticism policy, legal streaming rules, and liability limits for J-Anime Radar.",
            "body": DISCLAIMER_BODY,
            "updated": UPDATED,
        },
    ]
